/*!
* \defgroup main (main.c) Main Program
* \{
******************************************************************************
* \image html "Kopf_oZusatz_A4hoch_4C.jpg"
*
* \par Module Owner:
* Huf Group
*
* \par Initial Project:
* 1656.001 BSW
*
******************************************************************************
* \par Description:
* This module contains the global startup configuration function and
* the endless loop in which all tasks are called.
*
******************************************************************************
*
* %PCMS_HEADER_SUBSTITUTION_START:%
*
* Configuration Management Information Log (generated by Dimensions CM)
*
*
* CM Item: %PID:%
* Item name: %PM:%
* Location: %ARCHIVE:%
* Revision: %PR:%
* Date: %DATE:%
* Author: %AUTHOR:%
*
* %PCMS_HEADER_SUBSTITUTION_END:% *
******************************************************************************
*
* \par Layer:
* Operating System, Service Layer
*
* \par Compiler dialect:
* C99
*
* \par Controller:
* Independent
*
* \par Estimated resources:
* | Resource | Amount   | Remarks         |
* | ---------| -------- | ----------------|
* | ROM      | x Byte   | on x controller |
* | RAM      | y Byte   | on x controller |
* | NVRAM    | z Byte   | on x controller |
* | Runtime Init | X ms |                 |
* | Runtime Task | X ms |                 |
*
******************************************************************************/

/* Common declarations / Standard includes*/
/* ------------------- */
#include "Std_Types.h"          /* Standard include files */
/* Used interfaces from other modules */
#include "Os.h"
#include "EcuM.h"

/* Prototypes of all module internal (static) functions */
void init(void);
void main(void);

/*!
****************************************************************************
* \brief
* Application initialization after power up or reset.
*
* \details
* This function calls all initialization code from the used modules.
*
****************************************************************************
*
* \par Reentrance:
* Non Reentrant
* \par ASIL:
* QM
* \pre
* C startup code must been executed.
*
* \param[IN] 
* \param[OUT] 
* \param[IN/OUT] 
*
* \par Used global variables: 
* \parblock
* __Read:__
* 
* __Write:__
* 
* __Read/Write:__
* 
* \endparblock
*
* \par Called functions: 
* 
*
* \returns 
*
****************************************************************************
*
* \par Developer:
* <name>, PES-SWPS
* \par Tester:
* <name>
*
****************************************************************************/
/* polyspace < MISRA-C3:8.7 : Not a defect : Justify with annotations > External Usage dependent on project setup*/
void init(void)
{
	EcuM_Init();
}

/*!
****************************************************************************
* \brief
* main function for Huf operating system.
*
* \details
* This function initialize the uc after power on and calls the OS interface into
* a endless loop.
****************************************************************************
*
* \par Reentrance:
* Non Reentrant
* \par ASIL:
* QM
* \pre
* C startup code must been executed.
*
* \param[IN] 
* \param[OUT] 
* \param[IN/OUT] 
*
* \par Used global variables: 
* \parblock
* __Read:__
* 
* __Write:__
* 
* __Read/Write:__
* 
* \endparblock
*
* \par Called functions: 
* init()
*
* \returns 
*
****************************************************************************
*
* \par Developer:
* <name>, PES-SWPS
* \par Tester:
* <name>
*
****************************************************************************/
/* polyspace < MISRA-C3:D1.1 :  Not a defect : Justify with annotations> Main function should be void. */
void main(void)
{
    init();

#ifdef __POLYSPACE_RTE__
} 
/* polyspace < MISRA-C3:8.4: Not a defect : Justify with annotations > External Usage dependent on project setup*/
void main_OS_Loop(void) 
{
#endif /* __POLYSPACE_RTE__*/
	/* polyspace<RTE:NTL:Not a defect:No action planned> No error: The main loop. */
	while ( 1 )
	{
	   EcuM_LowPowerManager();
		OS_MAIN();
	}
}

/* %PCMS_HEADER_SUBSTITUTION_START:%
******************************************************************************
* Document Management Information Log (generated by Dimensions CM)
*
* Description:
* %PD:%
*
* Used by Baselines:
* %PIRB:%
*
* Used by Dimensions CM Projects:
* %PIRW:%
*
* Change History:
* %PL:%
*
* %PCMS_HEADER_SUBSTITUTION_END:%
*/