#ifndef SENSOR_AQUISITION_HA
#define SENSOR_AQUISITION_HA

#define U8_ER_MITTEL_ADD_COUNT          ((U8) 32)   /* count of samples for mean value (ER) */
#define U8_VR_MITTEL_ADD_COUNT          ((U8) 32)   /* count of samples for mean value (ER) */
#define U8_SENSORCALIBRATION_NOT_DONE   ((U8) 0)   /* count of samples for mean value (ER) */
#define U8_SENSORCALIBRATION_DONE       ((U8) 1)   /* count of samples for mean value (ER) */

#endif /*SENSOR_AQUISITION_CA*/


