/*!
 * \defgroup measure_supply (MeasureSupply.h) Supplies analogue Measurement values to state monitors
 * \{
 ******************************************************************************
 * \image html "Kopf_oZusatz_A4hoch_4C.jpg"
 *
 * \par Module Owner:
 *   Huf H&uuml;lsbeck & F&uuml;rst GmbH & Co. KG \n
 *   Steeger Str. 17 \n
 *   42551 Velbert \n
 *   Department PDE-S
 *
 * \par Initial Project:
 * BMW 1665.00x
 *
 ******************************************************************************
 * \par Description:
 * Supplies analogue Measurement values to state monitors
 *
 ******************************************************************************
 *
 * %PCMS_HEADER_SUBSTITUTION_START:%
 *
 * Configuration Management Information Log (generated by Dimensions CM)
 *
 *
 * CM Item: %PID:%
 * Item name: %PM:%
 * Location: %ARCHIVE:%
 * Revision: %PR:%
 * Date: %DATE:%
 * Author: %AUTHOR:%
 *
 * %PCMS_HEADER_SUBSTITUTION_END:% *
 *
 ******************************************************************************
 *
 * \par Layer:
 *    Service
 *
 * \par Controller:
 *    RL78
 *
 * \par Compiler Dialect:
 *    C90
 *
 * \par Resource Estimations:
 *    | Resource      | Amount         | Remarks         |
 *    | ------------- | -------------: | --------------- |
 *    | ROM           | 300 Byte     | estimation   |
 *    | RAM           | 0 Byte     | estimation   |
 *    | NVRAM         | 0 Byte   | estimation |
 *    | Runtime Init  | na    | there is no init  |
 *    | Runtime Task  | <210�s; normally <110�s    | longest wait times in microswitch readout with NFC collision  |
 *
 ******************************************************************************
 \defgroup measure_supply_det Details
 \ingroup measure_supply
 \{
*/



#ifndef MEASURESUPPLY_H_
#define MEASURESUPPLY_H_

#ifdef INTEGRATE_FROM_V4
#include "std_inc.h"
#endif

#ifndef INTEGRATE_FROM_V4
#include "Platform_Types.h"
#endif

#include "Std_Types.h"

#define ADC_INPUT_CH_VREFSH     1u
#define ADC_INPUT_CH_VREFSL     0u


/*-------------------------------------------------------------------------
Function : MeasureSupply_getUbattVoltage
Input    : void
Output   : U16 - current voltage measurement in ADC digits
Global   : -
External : -

Description: Executes voltage measurement and returns result
-------------------------------------------------------------------------*/
/* polyspace < MISRA-C3:8.5 : Not a defect : Justify with annotations > Function is declared once here */
extern U16 MeasureSupply_getUbattVoltage(void);
extern void Adc_init(void);
extern void REG_WRITE32_func(U32 address, U32 value);

#endif /* MEASURESUPPLY_H_ */
