/*
 ******************************************************************************
 * \image html "Kopf_oZusatz_A4hoch_4C.jpg"
 *
 * \par Module Owner:
 *   Huf H&uuml;lsbeck & F&uuml;rst GmbH & Co. KG \n
 *   Steeger Str. 17 \n
 *   42551 Velbert \n
 *   Department PDE-S
 *
 ******************************************************************************
 * \par Description:
 *
 * %PCMS_HEADER_SUBSTITUTION_START:% 
 ******************************************************************************
 * Document Management Information Log (generated by Dimensions CM)
 * 
 *
 *  CM Item:	%PID:%  
 *	Itemname:	%PM:%		
 *  Location:	%ARCHIVE:%
 *  Revision:	%PR:%
 *  Date:		%DATE:%
 *  Author:		%AUTHOR:%
 *
 * %PCMS_HEADER_SUBSTITUTION_END:%
 *
 ******************************************************************************/

#ifndef OC_SIGNALMNG_H_							/* To avoid double inclusion */
#define OC_SIGNALMNG_H_

#include "OC_DataSignalMng_Cfg.h"
#include "Platform_Types.h"
#include "S32K144.h"

/* polyspace:begin<MISRA-C3:D4.9 : Not a defect : Justify with annotations > Used for interface decoupling. */
/* polyspace+1 MISRA-C3:2.5 [Justified:Low] "Macro should be kept for future usage" */
#define START_LOW_RESOLUTION_ALARM(Timer, TimerVal_ms) timer_sw_start((Timer), SW_TIME_MS(TimerVal_ms));
/* polyspace:end<MISRA-C3:D4.9 : Not a defect : Justify with annotations > Used for interface decoupling. */

extern void OC_SignalMng_Task_V(void);

extern void OC_SignalMng_StartTx_V(void);

extern void OC_SignalMng_Init_V(void);

extern void OC_SignalMng_Trigger_WUP_Transmission(void);

extern void OC_SignalMng_Delay_WUP_Transmission(void);

extern OC_RET_EN_TYPE OC_SignalMng_SetSignalScalar_EN(ENUM_SYMBOLS_LIST A_Signal_name_EN, U8 *A_Signal_Value_PU8);

extern OC_MODE_EN_TYPE OC_SignalMng_getOcMode_EN(void);

extern OC_RET_EN_TYPE OC_SignalMng_SendSignalBinary_EN(ENUM_BINARY_TRANSMISSION_LIST Signal_Type_EN);

extern OC_RET_EN_TYPE OC_SignalMng_getTxStatus_EN(void);

extern OC_RET_EN_TYPE OC_SignalMng_setSignalFrame_EN(U8 *A_Data_PU8, U8 A_DataSize_U8);



#endif /* OC_SIGNALMNG */

/* %PCMS_HEADER_SUBSTITUTION_START:%
 ******************************************************************************
 * Document Management Information Log (generated by Dimensions CM)
 *
 *  Description:
 *  %PD:%
 *
 *  Used by Baselines:
 *  %PIRB:%
 *
 *  Used by Dimensions CM Projects:
 *  %PIRW:%
 *
 *  Change History:
 *  %PL:%
 *
 * %PCMS_HEADER_SUBSTITUTION_END:%
 */
