
/*
 ******************************************************************************
 * \image html "Kopf_oZusatz_A4hoch_4C.jpg"
 *
 * \par Module Owner:
 *   Huf H&uuml;lsbeck & F&uuml;rst GmbH & Co. KG \n
 *   Steeger Str. 17 \n
 *   42551 Velbert \n
 *   Department PDE-S
 *
 ******************************************************************************
 * \par Description:
 *
 * %PCMS_HEADER_SUBSTITUTION_START:% 
 ******************************************************************************
 * Document Management Information Log (generated by Dimensions CM)
 *
 *  CM Item:    %PID:%  
 *  Itemname:   %PM:%       
 *  Location:   %ARCHIVE:%
 *  Revision:   %PR:%
 *  Date:       %DATE:%
 *  Author:     %AUTHOR:%
 *
 * %PCMS_HEADER_SUBSTITUTION_END:%
 *
 ******************************************************************************/

#ifndef OC_SIGNALMNG_CFG_H_                                 /* To avoid double inclusion */
#define OC_SIGNALMNG_CFG_H_

#include "OC_Drv.h"
#include "Platform_Types.h"
#include "S32K144.h"


/******************** SIGNAL CONFIG ***********************/
/* polyspace+2 MISRA-C3:2.5 [Justified:Low] "Macro should be kept for future usage" */
#define MAX_FRAME_SIZE_U8 ((U8)174U)                        /* Max dimension of frame if all symbols are plotted */
#define SYMBOL_COUNT_U8 ((U8)64U)

/* polyspace<MISRA-C3:2.5 : Not a defect : may be used in a different configuration > */
#define SYMBOL_1_BYTE_U8 ((U8)1U)
/* polyspace<MISRA-C3:2.5 : Not a defect : may be used in a different configuration > */
#define SYMBOL_2_BYTE_U8 ((U8)2U)
/* polyspace<MISRA-C3:2.5 : Not a defect : may be used in a different configuration > */
#define SYMBOL_4_BYTE_U8 ((U8)4U)

typedef enum
{   SEND_KICK_EN,
    SEND_WUP_EN
}ENUM_BINARY_TRANSMISSION_LIST;

typedef enum
{
Start_Byte_E,     /* Byte 0*/
ADC_S1_E,     /* Byte 1 - Byte 2*/
ADC_S2_E,     /* Byte 3 - Byte 4*/
DSPO_S1_E,     /* Byte 5 - Byte 6*/
DSPO_S2_E,     /* Byte 7 - Byte 8*/
DSP_IN_E,     /* Byte 9*/
PARAM_E,     /* Byte 10*/
DACC_VALUE_E,     /* Byte 11*/
AMPO_S1_E,     /* Byte 12 - Byte 13*/
AMPO_S2_E,     /* Byte 14 - Byte 15*/
SSO_S1_E,     /* Byte 16 - Byte 17*/
SSO_S2_E,     /* Byte 18 - Byte 19*/
SLPO_S1_E,     /* Byte 20 - Byte 21*/
SLPO_S2_E,     /* Byte 22 - Byte 23*/
HPFO_S1_E,     /* Byte 24 - Byte 25*/
HPFO_S2_E,     /* Byte 26 - Byte 27*/
ThrCount_S1_E,     /* Byte 28*/
ThrCount_S2_E,     /* Byte 29*/
DevPercent_S1_E,     /* Byte 30*/
DevPercent_S2_E,     /* Byte 31*/
KickSigA_S1_E,     /* Byte 32 - Byte 33*/
KickSigA_S2_E,     /* Byte 34 - Byte 35*/
SumCountAT_S1_E,     /* Byte 36 - Byte 37*/
SumCountAT_S2_E,     /* Byte 38 - Byte 39*/
S1_OUT_E,     /* Byte 40*/
S2_OUT_E,     /* Byte 41*/
LL_OUT_E,     /* Byte 42*/
RESET_E,     /* Byte 43*/
Dummy_byte_1_E,     /* Byte 44*/
Dummy_byte_2_E,     /* Byte 45*/
Dummy_byte_3_E,     /* Byte 46*/
Dummy_byte_4_E,     /* Byte 47*/
Dummy_byte_5_E,     /* Byte 48*/
Dummy_byte_6_E,     /* Byte 49*/
Dummy_byte_7_E,     /* Byte 50*/
Dummy_byte_8_E,     /* Byte 51*/
Dummy_byte_9_E,     /* Byte 52*/
Dummy_byte_10_E,     /* Byte 53*/
Dummy_byte_11_E,     /* Byte 54*/
Dummy_byte_12_E,     /* Byte 55*/
Dummy_byte_13_E,     /* Byte 56*/
Dummy_byte_14_E,     /* Byte 57*/
Dummy_byte_15_E,     /* Byte 58*/
Dummy_byte_16_E,     /* Byte 59*/
Dummy_byte_17_E,     /* Byte 60*/
Dummy_byte_18_E,     /* Byte 61*/
Dummy_byte_19_E,     /* Byte 62*/
Dummy_byte_20_E,     /* Byte 63*/
Dummy_byte_21_E,     /* Byte 64*/
Dummy_byte_22_E,     /* Byte 65*/
Dummy_byte_23_E,     /* Byte 66*/
Dummy_byte_24_E,     /* Byte 67*/
Dummy_byte_25_E,     /* Byte 68*/
Dummy_byte_26_E,     /* Byte 69*/
Dummy_byte_27_E,     /* Byte 70*/
Dummy_byte_28_E,     /* Byte 71*/
Dummy_byte_29_E,     /* Byte 72*/
Dummy_byte_30_E,     /* Byte 73*/
Dummy_byte_31_E,     /* Byte 74*/
Dummy_byte_32_E,     /* Byte 75*/
Dummy_byte_33_E,     /* Byte 76*/
Dummy_byte_34_E,     /* Byte 77*/
Dummy_byte_35_E,     /* Byte 78*/
Stop_Byte_E,     /* Byte 79*/
    }ENUM_SYMBOLS_LIST;

static U8 SYMBOL_SIZE_AU8[SYMBOL_COUNT_U8] =
{
SYMBOL_1_BYTE_U8, /*Start_Byte_E*/
SYMBOL_2_BYTE_U8, /*ADC_S1*/
SYMBOL_2_BYTE_U8, /*ADC_S2*/
SYMBOL_2_BYTE_U8, /*DSPO_S1*/
SYMBOL_2_BYTE_U8, /*DSPO_S2*/
SYMBOL_1_BYTE_U8, /*DSP_IN*/
SYMBOL_1_BYTE_U8, /*PARAM*/
SYMBOL_2_BYTE_U8, /*DACC_VALUE*/
SYMBOL_2_BYTE_U8, /*AMPO_S1*/
SYMBOL_2_BYTE_U8, /*AMPO_S2*/
SYMBOL_2_BYTE_U8, /*SSO_S1*/
SYMBOL_2_BYTE_U8, /*SSO_S2*/
SYMBOL_2_BYTE_U8, /*SLPO_S1*/
SYMBOL_2_BYTE_U8, /*SLPO_S2*/
SYMBOL_2_BYTE_U8, /*HPFO_S1*/
SYMBOL_2_BYTE_U8, /*HPFO_S2*/
SYMBOL_1_BYTE_U8, /*ThrCount_S1*/
SYMBOL_1_BYTE_U8, /*ThrCount_S2*/
SYMBOL_1_BYTE_U8, /*DevPercent_S1*/
SYMBOL_1_BYTE_U8, /*DevPercent_S2*/
SYMBOL_2_BYTE_U8, /*KickSigA_S1*/
SYMBOL_2_BYTE_U8, /*KickSigA_S2*/
SYMBOL_2_BYTE_U8, /*SumCountAT_S1*/
SYMBOL_2_BYTE_U8, /*SumCountAT_S2*/
SYMBOL_1_BYTE_U8, /*S1_OUT*/
SYMBOL_1_BYTE_U8, /*S2_OUT*/
SYMBOL_1_BYTE_U8, /*LL_OUT*/
SYMBOL_1_BYTE_U8, /*RESET*/
SYMBOL_1_BYTE_U8, /*Dummy_byte_1*/
SYMBOL_1_BYTE_U8, /*Dummy_byte_2*/
SYMBOL_1_BYTE_U8, /*Dummy_byte_3*/
SYMBOL_1_BYTE_U8, /*Dummy_byte_4*/
SYMBOL_1_BYTE_U8, /*Dummy_byte_5*/
SYMBOL_1_BYTE_U8, /*Dummy_byte_6*/
SYMBOL_1_BYTE_U8, /*Dummy_byte_7*/
SYMBOL_1_BYTE_U8, /*Dummy_byte_8*/
SYMBOL_1_BYTE_U8, /*Dummy_byte_9*/
SYMBOL_1_BYTE_U8, /*Dummy_byte_10*/
SYMBOL_1_BYTE_U8, /*Dummy_byte_11*/
SYMBOL_1_BYTE_U8, /*Dummy_byte_12*/
SYMBOL_1_BYTE_U8, /*Dummy_byte_13*/
SYMBOL_1_BYTE_U8, /*Dummy_byte_14*/
SYMBOL_1_BYTE_U8, /*Dummy_byte_15*/
SYMBOL_1_BYTE_U8, /*Dummy_byte_16*/
SYMBOL_1_BYTE_U8, /*Dummy_byte_17*/
SYMBOL_1_BYTE_U8, /*Dummy_byte_18*/
SYMBOL_1_BYTE_U8, /*Dummy_byte_19*/
SYMBOL_1_BYTE_U8, /*Dummy_byte_20*/
SYMBOL_1_BYTE_U8, /*Dummy_byte_21*/
SYMBOL_1_BYTE_U8, /*Dummy_byte_22*/
SYMBOL_1_BYTE_U8, /*Dummy_byte_23*/
SYMBOL_1_BYTE_U8, /*Dummy_byte_24*/
SYMBOL_1_BYTE_U8, /*Dummy_byte_25*/
SYMBOL_1_BYTE_U8, /*Dummy_byte_26*/
SYMBOL_1_BYTE_U8, /*Dummy_byte_27*/
SYMBOL_1_BYTE_U8, /*Dummy_byte_28*/
SYMBOL_1_BYTE_U8, /*Dummy_byte_29*/
SYMBOL_1_BYTE_U8, /*Dummy_byte_30*/
SYMBOL_1_BYTE_U8, /*Dummy_byte_31*/
SYMBOL_1_BYTE_U8, /*Dummy_byte_32*/
SYMBOL_1_BYTE_U8, /*Dummy_byte_33*/
SYMBOL_1_BYTE_U8, /*Dummy_byte_34*/
SYMBOL_1_BYTE_U8, /*Dummy_byte_35*/
SYMBOL_1_BYTE_U8, /*Stop_Byte*/
};




/****************** NVM CONFIG *****************/
/* polyspace<MISRA-C3:2.5 : Not a defect : Used in other Modules > */
#define OC_BLOCK_ID         ((U8)OC_NVM_BLOCK_EN)
/* polyspace<MISRA-C3:2.5 : Not a defect : Used in other Modules > */
#define OC_NVM_BLOCK_SIZE   (24U)

#define OC_ROM_DEFAULT {\
.Array_Data_S =\
{\
.Data_AU8 =\
{\
0x53U, 0x01U, 0xFFU, 0xFFU,\
0x00U, 0x00U, 0x00U, 0x00U,\
0x00U, 0x00U, 0x00U, 0x00U,\
0x00U, 0x07U, 0x72U, 0x40U,\
0x00U, 0x00U, 0x02U, 0x80U,\
0x00U, 0x03U, 0xB9U, 0x20U,\
}\
}\
}\

/* polyspace<MISRA-C3:D4.9 : Not a defect : No actions planned  > # Replace pointer access for better readability  */
/* polyspace<MISRA-C3:2.5 : Not a defect : Used in other Modules > */
#define GET_OC_RAM_BLOCK_ADDRESS_PU8()\
{\
    (U8*)&OC_Ram_U\
}\

/* polyspace<MISRA-C3:11.8 : Not a defect : Justify with annotations > # Macro intention to get ROM Adress. No other possibility to get const adress*/
/* polyspace<MISRA-C3:D4.9 : Not a defect : No actions planned  > # Replace pointer access for better readability  */
/* polyspace<MISRA-C3:2.5 : Not a defect : Used in other Modules > */
#define GET_OC_ROM_BLOCK_ADDRESS_PCU8()\
{\
    (U8*)&OC_Rom_CU\
}\



/************************************* OC BLOCK **********************************/

typedef struct
{
    U8 Data_AU8[OC_NVM_BLOCK_SIZE];
} OC_BLOCK_DATA_ARRAY_S;

typedef struct
{
    U8 OcMode_U8;
    U8 OC_WUP_Enabled_U8;
    U8 AlignmentDummy[2];
    U32 Symbol_Selection_High_Value_U32;
    U32 Symbol_Selection_Low_Value_U32;
    U32 OC_Wup_Pulse_Length_U32;
    U32 OC_Wup_Pulse_Delay_Length_U32;
    U32 OC_Kick_Length_U32;

}OC_BLOCK_DATA_PARAMETERS_S;

/* polyspace<MISRA-C3:19.2 : Not a defect : Justify with annotations > Used for easy access of high Byte/ low byte of an U16 */
typedef union
{
    OC_BLOCK_DATA_ARRAY_S Array_Data_S;
    OC_BLOCK_DATA_PARAMETERS_S Parameter_Data_S;

} OC_BLOCK_DATA_U;

extern OC_BLOCK_DATA_U OC_Ram_U;
extern const OC_BLOCK_DATA_U OC_Rom_CU;


#endif /* OC_SIGNALMNG_CFG_H_ */

/* %PCMS_HEADER_SUBSTITUTION_START:%
 ******************************************************************************
 * Document Management Information Log (generated by Dimensions CM)
 *
 *  Description:
 *  %PD:%
 *
 *  Used by Baselines:
 *  %PIRB:%
 *
 *  Used by Dimensions CM Projects:
 *  %PIRW:%
 *
 *  Change History:
 *  %PL:%
 *
 * %PCMS_HEADER_SUBSTITUTION_END:%
 */
 






