/* polyspace+1 MISRA-C3:1.1 [Justified:Low] "All macro definitions are needed." */
/*!
* \defgroup
* \{
******************************************************************************
* \image html "Kopf_oZusatz_A4hoch_4C.jpg"
*
* \par Module Owner:
*       Huf H&uuml;lsbeck & F&uuml;rst GmbH & Co. KG \n
*       Steeger Str. 17 \n
*       42551 Velbert \n
*       DDepartment PDE-S
*
* \par Initial Project:
*       1642.001 KSGen3
*
******************************************************************************
* \par Description:
*
******************************************************************************
*
* %PCMS_HEADER_SUBSTITUTION_START:%
*
* Configuration Management Information Log (generated by Dimensions CM)
*
*
* CM Item: %PID:%
* Item name: %PM:%
* Location: %ARCHIVE:%
* Revision: %PR:%
* Date: %DATE:%
* Author: %AUTHOR:%
*
* %PCMS_HEADER_SUBSTITUTION_END:% *
******************************************************************************
*
* \par Layer:
*       Service layer
*
* \par Compiler dialect:
*       ANSI
*
* \par Controller:
*       Independant
*
 * \par Resources:
 *    | Resource      | Amount       | Remarks     |
 *    | ------------- | --------:    | ----------- |
 *    | ROM           |   592 Byte   |             |
 *    | RAM           |   339 Byte   |             |
 *    | EEPROM        |     0 Byte   |             |
 *    | Runtime Init  |  0.40 ms     |             |
 *    | Runtime Task  |  26.9 us     |             |
*
******************************************************************************/
/* polyspace+1 MISRA-C3:D4.4 [Justified:Low] "should be kept for future usage" */
/*#define OC_DEBUG_MODE*/
#include "Platform_Types.h"
#include "OC_DataSignalMng.h"
#include "OC_Drv.h"
#include "OC_Types.h"
#include "Platform_Types.h"
#include "S32K144.h"

/* ************************************************************************************
 *       REQUIRED DATA DECLARATION
 * ***********************************************************************************/

/* ************************************************************************************
 *       LOCAL CONSTANTS DEFINITION
 * ***********************************************************************************/


/* ************************************************************************************
 *       LOCAL TYPES DEFINITION
 * ***********************************************************************************/

/* ************************************************************************************
 *       LOCAL VARIABLES DEFINITION
 * ***********************************************************************************/

static OC_MODE_EN_TYPE Transfer_Mode_EN;

/* polyspace<MISRA-C3:8.7 : Not a defect : Used in other Modules > */
OC_BLOCK_DATA_U OC_Ram_U;
const OC_BLOCK_DATA_U OC_Rom_CU = OC_ROM_DEFAULT;

/* ************************************************************************************
 *       STATIC FUNCTION DECLARATION
 * ***********************************************************************************/

/* ************************************************************************************
 *      FUNCTION LIKE MACROS DEFINITION
 * ***********************************************************************************/

/* ************************************************************************************
 *       STATIC FUNCTION DEFINITION
 * ***********************************************************************************/

/***********************************************************
 *  Name                 : OC_SignalMng_setSignalFrame_EN
 *  Description          : Prepares the Frame for transmission
 *  Parameters           :
 *  [in]:      -
 *  [out]:     -   OC_RET_EN_TYPE OC_Status
 *  [in/out]:  -      
 *  Global variables     :
 *  [in]:      -
 *  [out]:     -   
 *  [in/out]:  -
 *  Return               : OC_RET_EN_TYPE
 *  Critical/explanation :
 *  Reentrant            : YES
 ***********************************************************/
/* Horia. TODO: pe asta o chemi!*/
OC_RET_EN_TYPE OC_SignalMng_setSignalFrame_EN(U8 *A_Data_PU8, U8 A_DataSize_U8)
{

    OC_RET_EN_TYPE A_OC_Status_EN=OC_RET_OK_E;

    if (Transfer_Mode_EN != OC_MODE_FRAME_E)
    {
        A_OC_Status_EN = OC_RET_ERR_E;
    }
    else
    {
        A_OC_Status_EN=OC_Drv_sendSignalData_EN(A_Data_PU8,A_DataSize_U8);
        Transfer_Mode_EN=OC_MODE_FRAME_E;
    }

    return A_OC_Status_EN;

}

/***********************************************************
 *  Name                 : OC_SignalMng_getTxStatus_EN
 *  Description          : Returns the current Transmission status
 *  Parameters           :
 *  [in]:      -
 *  [out]:     -
 *  [in/out]:  -
 *  Global variables     :
 *  [in]:      -
 *  [out]:     -
 *  [in/out]:  -
 *  Return               : OC_RET_EN_TYPE
 *  Critical/explanation :
 *  Reentrant            : YES
 ***********************************************************/


extern OC_RET_EN_TYPE  OC_SignalMng_getTxStatus_EN(void)
{
    return OC_Drv_getStatus_EN();
}

/***********************************************************
 *  Name                 : OC_SignalMng_getOcMode_EN
 *  Description          : Returns the current operation mode
 *  Parameters           :
 *  [in]:      -
 *  [out]:     -   OC_RET_EN_TYPE Transfer_Mode_EN
 *  [in/out]:  -
 *  Global variables     :
 *  [in]:      -
 *  [out]:     -
 *  [in/out]:  -
 *  Return               : OC_RET_EN_TYPE
 *  Critical/explanation :
 *  Reentrant            : YES
 ***********************************************************/

extern OC_MODE_EN_TYPE OC_SignalMng_getOcMode_EN(void)
{
    return Transfer_Mode_EN;
}

/***********************************************************
 *  Name                 : OC_SignalMng_StartTx_V
 *  Description          : start the Frame transmission
 *  Parameters           :
 *  [in]:      -
 *  [out]:     -
 *  [in/out]:  -
 *  Global variables     :
 *  [in]:      -   ENUM Transfer_Mode_EN
 *  [out]:     -
 *  [in/out]:  -
 *  Return               : None
 *  Critical/explanation :
 *  Reentrant            : NO
 ***********************************************************/
/* TODO: Trimite bufferul deja incarcat */
extern void OC_SignalMng_StartTx_V(void)
{
    if(Transfer_Mode_EN == OC_MODE_FRAME_E)
    {
        (void)OC_Drv_StartTx_EN();
    }
}


/***********************************************************
 *  Name                 : OC_SignalMng_Init_V
 *  Description          : Module Initialization
 *  Parameters           :
 *  [in]:      -
 *  [out]:     -
 *  [in/out]:  -
 *  Global variables     :
 *  [in]:      -
 *  [out]:     -
 *  [in/out]:  -
 *  Return               :
 *  Critical/explanation :
 *  Reentrant            : Yes
 ***********************************************************/
/* TODO: Transfer_Mode_EN = OC_MODE_FRAME_E instead of init*/
extern void OC_SignalMng_Init_V(void)
{
    Transfer_Mode_EN = OC_MODE_FRAME_E;
    OC_Drv_Init_V();
}

/* %PCMS_HEADER_SUBSTITUTION_START:%
 ******************************************************************************
 * Document Management Information Log (generated by Dimensions CM)
 *
 *  Description:
 *  %PD:%
 *
 *  Used by Baselines:
 *  %PIRB:%
 *
 *  Used by Dimensions CM Projects:
 *  %PIRW:%
 *
 *  Change History:
 *  %PL:%
 *
 * %PCMS_HEADER_SUBSTITUTION_END:%
 */
