/*!
* \defgroup
* \{
******************************************************************************
* \image html "Kopf_oZusatz_A4hoch_4C.jpg"
*
* \par Module Owner:
 *   Huf H&uuml;lsbeck & F&uuml;rst GmbH & Co. KG \n
 *   Steeger Str. 17 \n
 *   42551 Velbert \n
 *   Department PDE-S
 *
* \par Initial Project:
*   1642,001 KSGen3
*
******************************************************************************
* \par Description:
*
******************************************************************************
*
* %PCMS_HEADER_SUBSTITUTION_START:%
*
* Configuration Management Information Log (generated by Dimensions CM)
*
*
* CM Item: %PID:%
* Item name: %PM:%
* Location: %ARCHIVE:%
* Revision: %PR:%
* Date: %DATE:%
* Author: %AUTHOR:%
*
* %PCMS_HEADER_SUBSTITUTION_END:% *
******************************************************************************
*
* \par Layer:
*       MCAL
*
* \par Compiler dialect:
*       ANSI
*
* \par Controller:
*       S32K116
*
 * \par Resources:
 *    | Resource      | Amount    | Remarks     |
 *    | ------------- | --------: | ----------- |
 *    | ROM           | 925 Byte  |             |
 *    | RAM           |  13 Byte  |             |
 *    | EEPROM        |  24 Byte  |             |
 *    | Runtime Init  |  10.5 us  |             |
 *    | Runtime Task  |    X ms   |             |
*
******************************************************************************/
//#define SDA_DEBUG_MODE
/* Standard includes*/

/* required interfaces*/
#include "OC_Drv.h"
#include "OC_DataSignalMng.h"
#include "Platform_Types.h"
#include "S32K144.h"
/* provided interface*/

/* ************************************************************************************
 *       REQUIRED DATA DECLARATION
 * ***********************************************************************************/

/* ************************************************************************************
 *       LOCAL CONSTANTS DEFINITION
 * ***********************************************************************************/

/* ************************************************************************************
 *       LOCAL TYPES DEFINITION
 * ***********************************************************************************/

/* ************************************************************************************
 *       LOCAL VARIABLES DEFINITION
 * ***********************************************************************************/
static OC_RET_EN_TYPE Transmission_Status_EN;
static OC_OUTPUT_MODE_EN_TYPE Output_Peripheral_EN= OC_OUT_UNINITIALIZED_EN;
static U8 Transmission_Progress_U8;
static U8 Frame_Size_U8;
static U8 *TX_Frame_PU8;

/* ************************************************************************************
 *       STATIC FUNCTION DECLARATION
 * ***********************************************************************************/
static void OC_Drv_SendData_V(void);

/* ************************************************************************************
 *      FUNCTION LIKE MACROS DEFINITION
 * ***********************************************************************************/

/* ************************************************************************************
 *       STATIC FUNCTION DEFINITION
 * ***********************************************************************************/

/***********************************************************
 *  Name                 : OC_Drv_SendData_V
 *  Description          : Sets the next bytes of the transmission into the TX FIFO Buffer
 *  Parameters           :
 *  [in]:      -
 *  [out]:     -
 *  [in/out]:  -      
 *  Global variables     :
 *  [in]:      -
 *  [out]:     -   
 *  [in/out]:  -
 *  Return               : None
 *  Critical/explanation : Sends data via to OC Output pin when operating in UART mode and waits for the transmission to end.
 *  Reentrant            : NO
 ***********************************************************/

static void OC_Drv_SendData_V(void)
{
    U8 FIFO_Progress;
    Transmission_Status_EN=OC_RET_BUSY_E;
    if(Transmission_Progress_U8<= Frame_Size_U8)
    {
        for(FIFO_Progress=0;FIFO_Progress<FEATURE_LPUART_FIFO_SIZE;FIFO_Progress++)
        {
            if (Transmission_Progress_U8 != Frame_Size_U8)
            {
                /*"Write the next Byte into FIFO*/
                /* polyspace<MISRA-C3:18.1 : not a coding issue. Array Size is determined by configurations. > */
                /* polyspace<MISRA-C3:D4.1 : code runs as intended, there are nop runtime errors. > */
                LPUART0->DATA = TX_Frame_PU8[Transmission_Progress_U8]; /* polyspace RTE:IDP [Justified:Unset] " External pointer, responsibility fall on module calling the function to ensure Pointer size ( currently unused) " */
                Transmission_Progress_U8++;
            }
        }
    }
}

/* ************************************************************************************
 *       EXTERN FUNCTION DEFINITION
 * ***********************************************************************************/

/***********************************************************
 *  Name                 : LPUART0_RxTx_IRQHandler
 *  Description          : Interrupt Handler for the LPUART TX
 *  Parameters           :
 *  [in]:      -
 *  [out]:     -
 *  [in/out]:  -
 *  Global variables     :
 *  [in]:      -
 *  [out]:     -
 *  [in/out]:  -
 *  Return               : None
 *  Critical/explanation :
 *  Reentrant            : NO
 ***********************************************************/

void LPUART0_RxTx_IRQHandler(void)
{
    if (Transmission_Progress_U8 == Frame_Size_U8)
    {
        LPUART0->CTRL &=~ LPUART_CTRL_TCIE_MASK; // disable interrupts
        Transmission_Status_EN=OC_RET_OK_E; // transmitter available
    }
    else
    {
        OC_Drv_SendData_V();
    }
}

/***********************************************************
 *  Name                 : OC_Drv_Init_V
 *  Description          : Initializes the OC_Drv Module.
 *  Parameters           :
 *  [in]:      -
 *  [out]:     -
 *  [in/out]:  -      
 *  Global variables     :
 *  [in]:      -
 *  [out]:     -   
 *  [in/out]:  -
 *  Return               : None
 *  Critical/explanation :
 *  Reentrant            : NO
 ***********************************************************/

extern void OC_Drv_Init_V(void)
{
    PCC->PCCn[PCC_LPUART0_INDEX] &= ~PCC_PCCn_CGC_MASK; /* Ensure clk disabled for config */
    PCC->PCCn[PCC_LPUART0_INDEX] |= PCC_PCCn_PCS(2U); /* select SIRC/2 as the source clk */
    PCC->PCCn[PCC_LPUART0_INDEX] |= PCC_PCCn_CGC_MASK; /* Enable clk for UART */
    LPUART0->GLOBAL |= LPUART_GLOBAL_RST_MASK; /* perform UART0 SW Reset */
    LPUART0->GLOBAL &= ~LPUART_GLOBAL_RST_MASK; /* Disable UART0 SW Reset */
    LPUART0->BAUD = 0x02020001U; /*set the baud rate to 115200 , Oversampling ratio of 5, SBR =5*/

    LPUART0->FIFO |= LPUART_FIFO_TXFE_MASK; /* enable TX FIFO*/
    LPUART0->CTRL |= 0x00080000U; /* activate UART transmitter */

    /* Horia. TODO CHECK PRIO.*/
    /*set UART0 interrupt priority 2. The UART0 interrupt handler must have a lower priority than UART0 interrupt handler*/
    //S32_NVIC->IP[7U] |= S32_NVIC_IP_PRI_2(0x80U);
    S32_NVIC->IP[LPUART0_RxTx_IRQn] = 0x02;
    /*enable UART0 interrupt servicing*/
    S32_NVIC->ISER[(U32) LPUART0_RxTx_IRQn >> 5U] |= (1U << LPUART0_RxTx_IRQn);                 /* polyspace MISRA-C3:10.1 [Justified:Unset] "LPUART0_RxTx_IRQn is not an inappropiate essential type" */   /* polyspace MISRA-C3:12.2 [Justified:Unset] "Operation will not go outside of range" */
    Transmission_Status_EN = OC_RET_OK_E;
    Output_Peripheral_EN= OC_OUT_DISABLED_EN;
}

/***********************************************************
 *  Name                 : OC_Drv_sendSignalData_EN
 *  Description          : Prepares the module for frame transmission
 *  Parameters           :
 *  [in]:      -  ENUM Op_Mode_EN
 *             -  U8 Received_Value_U8
 *  [out]:     -  OC_RET_EN_TYPE Transmission_Status_EN
 *  [in/out]:  -      
 *  Global variables     :
 *  [in]:      -
 *  [out]:     -   
 *  [in/out]:  -
 *  Return               : OC_RET_EN_TYPE
 *  Critical/explanation :
 *  Reentrant            : NO
 ***********************************************************/
extern OC_RET_EN_TYPE  OC_Drv_sendSignalData_EN(U8 *A_SignalData_PU8, U8 A_DataSize_U8)
{
    if (Transmission_Status_EN == OC_RET_OK_E)
    {
        Frame_Size_U8=A_DataSize_U8;
        TX_Frame_PU8=A_SignalData_PU8;
    }
    return Transmission_Status_EN;
}

/***********************************************************
 *  Name                 : OC_Drv_getStatus_EN
 *  Description          : Returns the status of the transmission
 *  Parameters           :
 *  [in]:      -
 *  [out]:     - OC_RET_EN_TYPE Transmission_Status_EN
 *  [in/out]:  -
 *  Global variables     :
 *  [in]:      -
 *  [out]:     -
 *  [in/out]:  -
 *  Return               : OC_RET_EN_TYPE
 *  Critical/explanation :
 *  Reentrant            : NO
 ***********************************************************/

extern OC_RET_EN_TYPE OC_Drv_getStatus_EN(void)
{
    return Transmission_Status_EN;
}

/***********************************************************
 *  Name                 : OC_Drv_getOpMode_EN
 *  Description          : Returns the Transmission mode
 *  Parameters           :
 *  [in]:      -
 *  [out]:     - OC_RET_EN_TYPE Transmission_Status_EN
 *  [in/out]:  -
 *  Global variables     :
 *  [in]:      -
 *  [out]:     -
 *  [in/out]:  -
 *  Return               : OC_RET_EN_TYPE
 *  Critical/explanation :
 *  Reentrant            : NO
 ***********************************************************/

extern OC_OUTPUT_MODE_EN_TYPE OC_Drv_getOpMode_EN(void)
{
    return Output_Peripheral_EN;
}

/***********************************************************
 *  Name                 : OC_Drv_StartTx_EN
 *  Description          : Starts the Frame Transmission
 *  Parameters           :
 *  [in]:      -
 *  [out]:     - OC_RET_EN_TYPE Transmission_Status_EN
 *  [in/out]:  -
 *  Global variables     :
 *  [in]:      -
 *  [out]:     -
 *  [in/out]:  -
 *  Return               : OC_RET_EN_TYPE Transmission_Status_EN
 *  Critical/explanation :
 *  Reentrant            : NO
 ***********************************************************/

extern OC_RET_EN_TYPE OC_Drv_StartTx_EN(void)
{
    if(Transmission_Status_EN ==OC_RET_OK_E)
    {
        Transmission_Progress_U8=0U;
        OC_Drv_SendData_V();
        LPUART0->CTRL |= LPUART_CTRL_TCIE_MASK; // enable UART interrupt
    }
    return Transmission_Status_EN;
}

/***********************************************************
 *  Name                 : OC_Drv_stopTx_EN
 *  Description          : Stops the Frame transmission before it is finalized
 *  Parameters           :
 *  [in]:      -
 *  [out]:     - OC_RET_EN_TYPE Transmission_Status_EN
 *  [in/out]:  -
 *  Global variables     :
 *  [in]:      -
 *  [out]:     -
 *  [in/out]:  -
 *  Return               : OC_RET_EN_TYPE
 *  Critical/explanation :
 *  Reentrant            : NO
 ***********************************************************/
/*polyspace<MISRA-C3:8.7 : Not a defect : planned to possible be used in other modules too > */
extern OC_RET_EN_TYPE OC_Drv_stopTx_EN(void)
{
    OC_RET_EN_TYPE Local_Transmission_Status_EN=OC_RET_OK_E;

    if(Transmission_Status_EN==OC_RET_BUSY_E)
    {
        if (Output_Peripheral_EN==OC_OUT_LPUART_EN) // Frame mode
        {
            Transmission_Progress_U8 = Frame_Size_U8; /* prevent further Bytes to be added to the FIFO*/
            LPUART0->FIFO |= LPUART_FIFO_TXFLUSH_MASK; /* Clear remaining Bytes in FIFO*/
            /* The transmission is to be fully Stopped during the Interrupt, only then the system will be ready to accept a new Frame and the Transmission_Status_EN will be set to OC_RET_OK_E */
        }
        else //BinaryMode
        {
            /* End binary transmission */
            OC_Drv_EndBinaryTranmission_V();
        }
    }
    else
    {
        Local_Transmission_Status_EN=OC_RET_ERR_E; // transmission was off
    }
    return Local_Transmission_Status_EN;
}


/* %PCMS_HEADER_SUBSTITUTION_START:%
 ******************************************************************************
 * Document Management Information Log (generated by Dimensions CM)
 *
 *  Description:
 *  %PD:%
 *
 *  Used by Baselines:
 *  %PIRB:%
 *
 *  Used by Dimensions CM Projects:
 *  %PIRW:%
 *
 *  Change History:
 *  %PL:%
 *
 * %PCMS_HEADER_SUBSTITUTION_END:%
 */
