/*!
* \defgroup module (MOD_SERV_BATTERY_MONITORING)
* This module handles the detection of the battery's voltage status.
* \
******************************************************************************
* \image html "Kopf_oZusatz_A4hoch_4C.jpg"
*
* \par Module Owner:
* Huf Group
*
* \par Initial Project:
* 1656.001 BSW
*
******************************************************************************
* \par Description:
* This is the header file for the MOD_SERV_BATTERY_MONITORING module.
* Contains definitions for types, variables and global functions from BatMon.c
* and all required header files.
*
******************************************************************************
*
* %PCMS_HEADER_SUBSTITUTION_START:%
*
* Configuration Management Information Log (generated by Dimensions CM)
*
*
* CM Item: %PID:%
* Item name: %PM:%
* Location: %ARCHIVE:%
* Revision: %PR:%
* Date: %DATE:%
* Author: %AUTHOR:%
*
* %PCMS_HEADER_SUBSTITUTION_END:% *
******************************************************************************
*
* \par Layer:
* Service Layer
*
* \par Compiler dialect:
* C99
*
* \par Controller:
* Independent
*
* \par Estimated resources:
* | Resource | Amount   | Remarks         |
* | ---------| -------- | ----------------|
* | ROM      | x Byte   | on x controller |
* | RAM      | y Byte   | on x controller |
* | NVRAM    | z Byte   | on x controller |
* | Runtime Init | X ms |                 |
* | Runtime Task | X ms |                 |
*
******************************************************************************/

#ifndef MOD_BAT_MON_H_							/* To avoid double inclusion */
#define MOD_BAT_MON_H_


#endif /* MOD_BAT_MON_H_ */

/* %PCMS_HEADER_SUBSTITUTION_START:%
******************************************************************************
* Document Management Information Log (generated by Dimensions CM)
*
* Description:
* %PD:%
*
* Used by Baselines:
* %PIRB:%
*
* Used by Dimensions CM Projects:
* %PIRW:%
*
* Change History:
* %PL:%
*
* %PCMS_HEADER_SUBSTITUTION_END:%
*/
