 /* polyspace MISRA-C3:D4.10 [Not a defect:Unset] "Module included just by EcuM, it is part of memory mapping strategy" */
/*******************************************************************************
* \image html "Kopf_oZusatz_A4hoch_4C.jpg"
*
* \par Module Owner:
* Huf Huelsbeck & Fuerst GmbH & Co.KG \n
* Steeger Str. 17 \n
* 42551 Velbert \n
* Department PDE - S
*
******************************************************************************
* \par Description:
* Generated memory map file for EcuM
* Implementation based on Autosar 4.2 specifications   \n
*
* % PCMS_HEADER_SUBSTITUTION_START:%
******************************************************************************
*Document Management Information Log(generated by Dimensions CM)
*
*
*CM Item:   % PID:%
*Itemname:  % PM:%
*Location:  % ARCHIVE:%
*Revision:  % PR:%
*Date:      % DATE:%
*Author:    % AUTHOR:%
*
* % PCMS_HEADER_SUBSTITUTION_END:%
*
******************************************************************************/

#define ECUM_MEMMAP_ERROR

/* polyspace-begin MISRA-C3:20.5 [Not a defect:Unset] "#undef is part of the memory mapping strategy, undefined macro is not necessary anymore" */
#if defined( ECUM_LAST_SHUTDOWN_TARGET_START_SEC_VAR )
/* #pragma <enter your compiler specific pragma> */
/* polyspace +1 MISRA-C3:D1.1 [Not a defect:Unset] "pragma used to place a variable into a no init area" */
#pragma object_attribute=__no_init
# undef ECUM_LAST_SHUTDOWN_TARGET_START_SEC_VAR
# undef ECUM_MEMMAP_ERROR

#endif

#if defined( ECUM_LAST_SHUTDOWN_TARGET_STOP_SEC_VAR )
   /* #pragma <enter your compiler specific pragma> */
# undef ECUM_LAST_SHUTDOWN_TARGET_STOP_SEC_VAR
# undef ECUM_MEMMAP_ERROR

#endif

#if defined( ECUM_LAST_SHUTDOWN_MODE_START_SEC_VAR )
/* #pragma <enter your compiler specific pragma> */
/* polyspace +1 MISRA-C3:D1.1 [Not a defect:Unset] "pragma used to place a variable into a no init area" */
#pragma object_attribute=__no_init
# undef ECUM_LAST_SHUTDOWN_MODE_START_SEC_VAR
# undef ECUM_MEMMAP_ERROR

#endif

#if defined( ECUM_LAST_SHUTDOWN_MODE_STOP_SEC_VAR )
   /* #pragma <enter your compiler specific pragma> */
# undef ECUM_LAST_SHUTDOWN_MODE_STOP_SEC_VAR
# undef ECUM_MEMMAP_ERROR

#endif

#if defined( ECUM_INTENDED_RESTART_FLAG_START_SEC_VAR )
/* #pragma <enter your compiler specific pragma> */
/* polyspace +1 MISRA-C3:D1.1 [Not a defect:Unset] "pragma used to place a variable into a no init area" */
#pragma object_attribute=__no_init
# undef ECUM_INTENDED_RESTART_FLAG_START_SEC_VAR
# undef ECUM_MEMMAP_ERROR

#endif

#if defined( ECUM_INTENDED_RESTART_FLAG_STOP_SEC_VAR )
   /* #pragma <enter your compiler specific pragma> */
# undef ECUM_INTENDED_RESTART_FLAG_STOP_SEC_VAR
# undef ECUM_MEMMAP_ERROR

#endif
/* polyspace-end MISRA-C3:20.5 [Not a defect:Unset] "#undef is part of the memory mapping strategy, undefined macro is not necessary anymore" */

#if defined( ECUM_MEMMAP_ERROR )
# error "Error in MemMap.h: MemMap section is not included!"
#endif


 /* %PCMS_HEADER_SUBSTITUTION_START:%
  ******************************************************************************
  * Document Management Information Log (generated by Dimensions CM)
  *
  *  Description:
  *  %PD:%
  *
  *  Used by Baselines:
  *  %PIRB:%
  *
  *  Used by Dimensions CM Projects:
  *  %PIRW:%
  *
  *  Change History:
  *  %PL:%
  *
  * %PCMS_HEADER_SUBSTITUTION_END:%
  */