/*
*!
* \defgroup <module_group (MOD_) Module purpose>
* \{
******************************************************************************
* \image html "Kopf_oZusatz_A4hoch_4C.jpg"
*
* \par Module Owner:
* Huf Huelsbeck & Fuerst GmbH & Co.KG \n
* Steeger Str. 17 \n
* 42551 Velbert \n
* Department PDE - S
*
******************************************************************************
*
* \par Purpose:
* Post build configuration file for EcuM
* Service Layer(AUTOSAR 4.2)
*
* \par Compiler:

*IAR
*
* \par Controller:

*Independent
*
* \par Resources:

*    | Resource     | Amount    | Remarks|
*    | -------------| ----------| -------|
*    | ROM          | x Byte    |        |
*    | CODE         | x Byte    |        |
*    | RAM          | x Byte    |        |
*    | EEPROM       | x Byte    |        |
*    | Runtime Init | X ms      |        |
*    | Runtime Task | X ms      |        |
*
* \par Quality:

*    | Factor            | Excl  | Good  | Fair  | Poor  |
*    | ----------------- | ----: | ----: | ----: | ----: |
*    | _Maintainability_ | 0 %   | 0 %   | 0 %   | 0 %   |  
*    | Analyzability     | 0 %   | 0 %   | 0 %   | 0 %   |
*    | Changeability     | 0 %   | 0 %   | 0 %   | 0 %   |
*    | Stability         | 0 %   | 0 %   | 0 %   | 0 %   |
*    | Testability       | 0 %   | 0 %   | 0 %   | 0 %   |
*
* \par MISRA rules violations:

*     \li none
*
******************************************************************************
*
* \attention
*   \li This file is generated from the configuration tool and needs to be adapted
* according to project specification
*
******************************************************************************
* % PCMS_HEADER_SUBSTITUTION_START:%
*
*Document Management Information Log(generated by Dimensions CM)
*
*
*CM Item:   % PID:%
*Itemname:  % PM:%
*Location:  % ARCHIVE:%
*Revision:  % PR:%
*Date:      % DATE:%
*Author:    % AUTHOR:%
*
* % PCMS_HEADER_SUBSTITUTION_END:%
*
******************************************************************************/

/*!
 \defgroup module_group_det Details
 \ingroup module_group
 \{
*/


#include "EcuM_Cbk.h"

/* [SWS_EcuM_02801] */
/* [SWS_EcuM_00800] */
/* [SWS_EcuM_00793] */
const EcuM_ConfigType EcuM_Config_Set = {NULL };


/* %PCMS_HEADER_SUBSTITUTION_START:%
 ******************************************************************************
 * Document Management Information Log (generated by Dimensions CM)
 *
 *  Description:
 *  %PD:%
 *
 *  Used by Baselines:
 *  %PIRB:%
 *
 *  Used by Dimensions CM Projects:
 *  %PIRW:%
 *
 *  Change History:
 *  %PL:%
 *
 * %PCMS_HEADER_SUBSTITUTION_END:%
 */
