/*
 ******************************************************************************
 * \image html "Kopf_oZusatz_A4hoch_4C.jpg"
 *
 * \par Module Owner:
 * Huf Huelsbeck & Fuerst GmbH & Co.KG \n
 * Steeger Str. 17 \n
 * 42551 Velbert \n
 * Department PDE - S
 *
 ******************************************************************************
 * \par Description:
 * Generated configuration file for EcuM
 * Implementation based on Autosar 4.2 specifications   \n
 *
 * % PCMS_HEADER_SUBSTITUTION_START:%
 ******************************************************************************
 *Document Management Information Log(generated by Dimensions CM)
 *
 *
 *CM Item:   % PID:%
 *Itemname:  % PM:%
 *Location:  % ARCHIVE:%
 *Revision:  % PR:%
 *Date:      % DATE:%
 *Author:    % AUTHOR:%
 *
 * % PCMS_HEADER_SUBSTITUTION_END:%
 *
 ******************************************************************************/ 

#ifndef  ECUM_CFG_H_         /* To avoid double inclusion */
#define  ECUM_CFG_H_

/* EcuMGeneral */
/* polyspace-begin MISRA-C3:2.5 [Not a defect:Unset] "Macros used into integration code or defined for future implementation" */
#define ECUM_DEV_ERROR_DETECT_ENABLED     STD_OFF
#define ECUM_INCLUDE_DET                  STD_OFF /* this parameter must be set to STD_OFF - for the moment DET is not automatically initialized by EcuM, user can initialize it if needed into the callout functions */
/* [SWS_EcuM_00594] */
#define ECUM_MAIN_FUNCTION_PERIOD         (U8)10      /* ms */ 
#define ECUM_VERSION_INFO_API_ENABLED     STD_OFF

/* EcuMFixedGeneral */
#define ECUM_INCLUDE_COMM_CFG             STD_ON 
#define ECUM_TTII_ENABLED                 STD_OFF /* this parameter must be set to STD_OFF because TTII is not supported by EcuM */
#define ECUM_TTII_WAKEUP_SOURCE           ECUM_WKSOURCE_NONE/* this parameter must be set to ECUM_WKSOURCE_NONE because TTII is not supported */

/* EcuMFixedConfiguration */
#define ECUM_NVM_WRITE_ALL_ENABLED        STD_OFF   /*EcuM doesn't call NvM WriteAll before Sleep or Shutdown */
#define ECUM_RUN_MINIMUM_DURATION         (U16)200    /* ms */ /* Duration for which the ECU State Manager will stay in RUN state even when no one requests RUN. This duration should be long at least as long as a SW-Cs needs to request RUN */
#define ECUM_RUN_TIMEOUT_VALUE            (U16)(ECUM_RUN_MINIMUM_DURATION/ECUM_MAIN_FUNCTION_PERIOD)

/* [SWS_EcuM_00232] */
#define ECUM_DEFAULT_SHUTDOWN_TARGET        ECUM_STATE_SLEEP
#define ECUM_DEFAULT_SHUTDOWN_MODE          ECUM_SLEEP_LPM
#define ECUM_NORMAL_MCU_MODE                0xFF

#define ECUM_RESET_REASON_OF_WAKEUP_ENABLE  STD_OFF /* STD_ON - activates the handle for detecting the reset reason after reset into the startup phase
                                                         STD_OFF - the reset reason is not detected, it will always return ECUM_WKSOURCE_RESET
                                                         This parameter must be set to STD_ON if the project contains wake up sources with integrated power control */
#define ECUM_VALIDATION_TIMEOUT_ENABLED     STD_OFF /* STD_ON - activates the wake up validation protocol, it shall be enabled when at least one wake up source needs validation
															STD_OFF - wake up validation protocol is not active, all the wake ups are considered valid */

#define ECUM_CALLOUT_DRIVER_INIT_ZERO       STD_ON    /* STD_ON - EcuM_AL_DriverInitZero is active and called by EcuM at startup
                                                            STD_OFF - EcuM_AL_DriverInitZero is not active  */
#define ECUM_CALLOUT_DRIVER_INIT_ONE        STD_ON    /* STD_ON - EcuM_AL_DriverInitOne is active and called by EcuM at startup
                                                            STD_OFF - EcuM_AL_DriverInitOne is not active  */
#define ECUM_CALLOUT_DRIVER_INIT_TWO        STD_ON    /* STD_ON - EcuM_AL_DriverInitTwo is active and called by EcuM at startup
                                                            STD_OFF - EcuM_AL_DriverInitTwo is not active  */
#define ECUM_CALLOUT_DRIVER_INIT_THREE      STD_ON    /* STD_ON - EcuM_AL_DriverInitThree is active and called by EcuM at startup
                                                            STD_OFF - EcuM_AL_DriverInitThree is not active  */

#define ECUM_WAKEUP_SOURCES_ON_POLLING      STD_OFF   /* this parameter shall be set to STD_OFF - polling wake up sources is not supported */
#define ECUM_POLLING_MODE                   0xFE         /* this parameter is used to configure MCU clock when entering into SLEEP II if it is necessary */
#define ECUM_CURRENT_MODE_CALLOUT           STD_OFF  /* STD_ON - an callout will be called when EcuM mode is changed
                                                            STD_OFF - the callout is not called */
/* [SWS_EcuM_02165] */
/* [SWS_EcuM_02166] */
/* [SWS_EcuMf_00002] */
/* Range of EcuM_WakeupSourceType */
/* The list can be extended here with new wake up sources using bits 5 up to 31 */
#define ECUM_WKSOURCE_NONE                          (EcuM_WakeupSourceType)(0x00000000UL)
#define ECUM_WKSOURCE_ALL_SOURCES                   (EcuM_WakeupSourceType)(1023UL)
#define ECUM_WKSOURCE_POWER                         (EcuM_WakeupSourceType)(1UL)
#define ECUM_WKSOURCE_RESET                         (EcuM_WakeupSourceType)(2UL)
#define ECUM_WKSOURCE_INTERNAL_RESET                (EcuM_WakeupSourceType)(4UL)
#define ECUM_WKSOURCE_INTERNAL_WDG                  (EcuM_WakeupSourceType)(8UL)
#define ECUM_WKSOURCE_EXTERNAL_WDG                  (EcuM_WakeupSourceType)(16UL)
#define ECUM_WAKEUP_CAN                  (EcuM_WakeupSourceType)(32UL)
#define ECUM_WAKEUP_ALGO                  (EcuM_WakeupSourceType)(64UL)
#define ECUM_WAKEUP_LED                  (EcuM_WakeupSourceType)(128UL)
#define ECUM_WAKEUP_NFC_LIB                  (EcuM_WakeupSourceType)(256UL)
#define ECUM_WAKEUP_NFC_APP                  (EcuM_WakeupSourceType)(512UL)

#define ECUM_NO_OF_WAKEUP_SOURCES    (U8)(10u)

/* SWR_673 */
/* sleep modes - are set according to the corresponding MCU modes */
#define ECUM_SLEEP_LPM            (EcuM_SleepModeType)(0u)
#define ECUM_UNUSED_SLEEP_MODE    (EcuM_SleepModeType)(0xFFu)

#define ECUM_NO_OF_SLEEP_MODES       (EcuM_SleepModeType)(1u)

/* Unique value for each user, the list can be extended here */
/* [SWS_EcuM_00487] */
#define ECUM_USER_KEEP_RUN_STATE                 (EcuM_UserType)(0u)
#define E_ECUM_VR_SENSOR                 (EcuM_UserType)(1u)
#define E_ECUM_ER_SENSOR                 (EcuM_UserType)(2u)
#define E_ECUM_INDUCTIVE                 (EcuM_UserType)(3u)
#define E_ECUM_VOLT_MON                 (EcuM_UserType)(4u)
#define E_ECUM_VA_LED                 (EcuM_UserType)(5u)
#define E_ECUM_NFC_LIB                 (EcuM_UserType)(6u)
#define E_ECUM_NFC_APP                 (EcuM_UserType)(7u)

#define ECUM_NO_OF_USERS             (EcuM_UserType)(8u)

#define ECUM_NO_OF_COMM_CHANNELS     (1u)
#define ECUM_UNDEFINED_COMM_CHANNEL  0XFFu
/* polyspace-end MISRA-C3:2.5 [Not a defect:Unset] "Macros used into integration code or defined for future implementation" */

#endif   /* ECUM_CFG_H_ */



/* %PCMS_HEADER_SUBSTITUTION_START:%
 ******************************************************************************
 * Document Management Information Log (generated by Dimensions CM)
 *
 *  Description:
 *  %PD:%
 *
 *  Used by Baselines:
 *  %PIRB:%
 *
 *  Used by Dimensions CM Projects:
 *  %PIRW:%
 *
 *  Change History:
 *  %PL:%
 *
 * %PCMS_HEADER_SUBSTITUTION_END:%
 */
