/*!
 * \defgroup MOD_SERV_OS (Os_Cfg.h)
 * \{
 ******************************************************************************
 * \image html "Kopf_oZusatz_A4hoch_4C.jpg"
 *
 * \par Module Owner:
 * Huf Group
 *
 * \par Initial Project:
 * 1656.001 BSW
 *
 ******************************************************************************
 * \par Description:
 * Generated configuration header file for Serv OS.
 *
 ******************************************************************************
 *
 * %PCMS_HEADER_SUBSTITUTION_START:%
 *
 * Configuration Management Information Log (generated by Dimensions CM)
 *
 *
 * CM Item: %PID:%
 * Item name: %PM:%
 * Location: %ARCHIVE:%
 * Revision: %PR:%
 * Date: %DATE:%
 * Author: %AUTHOR:%
 *
 * %PCMS_HEADER_SUBSTITUTION_END:% *
 ******************************************************************************
 *
 * \par Layer:
 * Operating System, Service Layer
 *
 * \par Compiler dialect:
 * C99
 *
 * \par Controller:
 * Independent
 *
 * \par Estimated resources:
 * | Resource | Amount   | Remarks         |
 * | ---------| -------- | ----------------|
 * | ROM      | x Byte   | on x controller |
 * | RAM      | y Byte   | on x controller |
 * | NVRAM    | z Byte   | on x controller |
 * | Runtime Init | X ms |                 |
 * | Runtime Task | X ms |                 |
 *
 ******************************************************************************/
#ifndef OS_GENCFG_H_                   /* To avoid double inclusion */
#define OS_GENCFG_H_

#include "Os_CommonCfg.h"
#include "Os_Mcal.h"

/*[SWPS_SWS_SERVOS_00002], [SWPS_SWS_SERVOS_00003], [SWPS_SWS_SERVOS_00004], [SWPS_SWS_SERVOS_00005], [SWPS_SWS_SERVOS_00006], [SWPS_SWS_SERVOS_00007], [SWPS_SWS_SERVOS_00014], [SWPS_SWS_SERVOS_00015], [SWPS_SWS_SERVOS_00016], [SWPS_SWS_SERVOS_00017], [SWPS_SWS_SERVOS_00018], [SWPS_SWS_SERVOS_00022] */
/* polyspace +5 MISRA-C3:D4.9 [Not a defect:Unset] "Macros used to facilitate an easier adaptation" */
/* polyspace +3 MISRA-C3:2.5 [Not a defect:Unset] "The macro is used during integration phase" */
/*Macro used to convert time from ticks to milliseconds. This macro must only be used for constants times*/
#define OS_TICKS2MS_SystemTimer(tick) (((U32)((U32)(tick) * (U32)OS_TICK_TIME_US))/ 1000U)
#define OS_BACKGROUND_TASK_FUNC() BackgroundTask()        /*[SWPS_SWS_SERVOS_00114]*/

/* Conformance class: 
* BCC1(only basic tasks, limited to one activation request per task and one task per priority, while all tasks have different priorities)
* BCC2(like BCC1, plus more than one task per priority possible and multiple requesting of task activation allowed) */
#define OS_CONF_CLASS BCC1         /*[SWPS_SWS_SERVOS_00111]*/

/*Enable non-cyclic tasks*/
/*[SWPS_SWS_SERVOS_00007], [SWPS_SWS_SERVOS_00019], [SWPS_SWS_SERVOS_00020] */
#define OS_ENABLE_NON_CYCLIC_TASKS STD_OFF

/*Enable not nestable API for enable/disable interrupts - [SWPS_SWS_SERVOS_00110] */
#define OS_ENABLE_NOT_NESTABLE_INT_API STD_OFF
/*Enable pre/post task hooks [SWPS_SWS_SERVOS_00105]*/
#define OS_ENABLE_TASK_HOOKS STD_OFF
/*Enable startup hook - [SWPS_SWS_SERVOS_00107]*/
#define OS_ENABLE_STARTUP_HOOK STD_OFF
/* Enable/Disable  GetElapsedValue API - [SWPS_SWS_SERVOS_00112] */
#define OS_GET_ELAPSED_VAL_API STD_ON
/* Enable/Disable  GetCounterValue API - [SWPS_SWS_SERVOS_00113] */
#define OS_GET_COUNTER_VAL_API STD_ON

/*Enable/disable single alarms [SWPS_SWS_SERVOS_00125]*/
#define OS_SINGLE_ALARMS_ENABLED_CFG STD_OFF

#define OS_NO_OF_CYCLIC_TASKS 5u

/* polyspace +2 MISRA-C3:2.5 [Not a defect:Unset] "The macro is used during integration phase" */
/*Define counters' IDs*/
#define SystemTimer      0x00u

/* polyspace-begin MISRA-C3:2.5 [Not a defect:Unset] "Task IDs are used into integration" */
#define OS_TASK_ID_Task_5ms 0u
#define OS_TASK_ID_Task_10ms 1u
#define OS_TASK_ID_Task_25ms 2u
#define OS_TASK_ID_Task_100ms 3u
#define OS_TASK_ID_Task_2_5ms 4u
/* polyspace-end MISRA-C3:2.5 [Not a defect:Unset] "Task IDs are used into integration" */
#define OS_TASK_ID_Idle 0xFFu

#define NUMBER_OF_CYCLIC_ALARMS 5u

/* Number of distinct task priorities */
#define OS_NO_OF_PRIORITIES 5u

/* Enable/Disable Get/ReleaseResource APIs - [SWPS_SWS_SERVOS_00106]*/
#define OS_GET_RELEASE_RESOURCE_API STD_ON
#define RES_SCHEDULER 0u

/* List of priorities sorted: index 0 contains the highest priority value, index <OS_NO_OF_PRIORITIES - 1> contains
 * the lowest priority value */
extern const U8 Os_SortedPriorityList[OS_NO_OF_PRIORITIES];

/* Task configuration */
extern const Os_TaskCfgDataType Os_TaskCfgData[OS_NO_OF_CYCLIC_TASKS];

extern const Os_CyclicAlarmCfgDataType Os_CyclicAlarmCfgData[NUMBER_OF_CYCLIC_ALARMS];

/* polyspace-begin MISRA-C3:8.5 [Not a defect:Unset] "Was decided that all configured functions be declared as extern into the configuration file" */
/* polyspace-begin MISRA-C3:5.1 [Not a defect:Unset] "C99 standard is used to compile, Huf naming convention" */
extern TASK(Task_5ms);
extern TASK(Task_10ms);
extern TASK(Task_25ms);
extern TASK(Task_100ms);
extern TASK(Task_2_5ms);
extern void BackgroundTask(void);

/* polyspace-end MISRA-C3:8.5 [Not a defect:Unset] "Was decided that all configured functions be declared as extern into the configuration file" */
/* polyspace-begin MISRA-C3:5.1 [Not a defect:Unset] "C99 standard is used to compile, Huf naming convention" */

#endif /* OS_GENCFG_H_ */

/* %PCMS_HEADER_SUBSTITUTION_START:%
 ******************************************************************************
 * Document Management Information Log (generated by Dimensions CM)
 *
 * Description:
 * %PD:%
 *
 * Used by Baselines:
 * %PIRB:%
 *
 * Used by Dimensions CM Projects:
 * %PIRW:%
 *
 * Change History:
 * %PL:%
 *
 * %PCMS_HEADER_SUBSTITUTION_END:%
 */
