/* polyspace MISRA-C3:1.1 [Justified:Low]"The defined macros are controller specific macros from registers header file" */
/*!
 * \defgroup MOD_SERV_OS (Os_LCfg.c)
 * \{
 ******************************************************************************
 * \image html "Kopf_oZusatz_A4hoch_4C.jpg"
 *
 * \par Module Owner:
 * Huf Group
 *
 * \par Initial Project:
 * 1656.001 BSW
 *
 ******************************************************************************
 * \par Description:
 * Generated configuration source file for Serv OS.
 *
 ******************************************************************************
 *
 * %PCMS_HEADER_SUBSTITUTION_START:%
 *
 * Configuration Management Information Log (generated by Dimensions CM)
 *
 *
 * CM Item: %PID:%
 * Item name: %PM:%
 * Location: %ARCHIVE:%
 * Revision: %PR:%
 * Date: %DATE:%
 * Author: %AUTHOR:%
 *
 * %PCMS_HEADER_SUBSTITUTION_END:% *
 ******************************************************************************
 *
 * \par Layer:
 * Operating System, Service Layer
 *
 * \par Compiler dialect:
 * C99
 *
 * \par Controller:
 * Independent
 *
 * \par Estimated resources:
 * | Resource | Amount   | Remarks         |
 * | ---------| -------- | ----------------|
 * | ROM      | x Byte   | on x controller |
 * | RAM      | y Byte   | on x controller |
 * | NVRAM    | z Byte   | on x controller |
 * | Runtime Init | X ms |                 |
 * | Runtime Task | X ms |                 |
 *
 ******************************************************************************/
/* Include files */
#include "Os.h"

/* [SWPS_SWS_SERVOS_00115], [SWPS_SWS_SERVOS_00116], [SWPS_SWS_SERVOS_00117],[SWPS_SWS_SERVOS_00118], [SWPS_SWS_SERVOS_00119], [SWPS_SWS_SERVOS_00120], [SWPS_SWS_SERVOS_00121], [SWPS_SWS_SERVOS_00122], [SWPS_SWS_SERVOS_00123], [SWPS_SWS_SERVOS_00124] */ 
const U8 Os_SortedPriorityList[OS_NO_OF_PRIORITIES] = {10u, 8u, 6u, 2u, 1u};

const Os_TaskCfgDataType Os_TaskCfgData[OS_NO_OF_CYCLIC_TASKS] = {
/* functionPointer priority prioIndex scheduling noAllowedActivations alarmID */
	{   &Task_5msfunc, 10u, 0u, NON_PREEMPTIVE, 1u, 0u}, /*Task_5ms*/
	{   &Task_10msfunc, 8u, 1u, NON_PREEMPTIVE, 1u, 1u}, /*Task_10ms*/
	{   &Task_25msfunc, 6u, 2u, NON_PREEMPTIVE, 1u, 2u}, /*Task_25ms*/
	{   &Task_100msfunc, 2u, 3u, NON_PREEMPTIVE, 1u, 3u}, /*Task_100ms*/
	{   &Task_2_5msfunc, 1u, 4u, NON_PREEMPTIVE, 1u, 4u} /*Task_2_5ms*/
};

const Os_CyclicAlarmCfgDataType Os_CyclicAlarmCfgData[NUMBER_OF_CYCLIC_ALARMS] = {
/* counterRef cycleTime initialCycleTime taskID */
	{   &Os_TickCounter, 2u, 1u, 0u},
	{   &Os_TickCounter, 4u, 2u, 1u},
	{   &Os_TickCounter, 10u, 10u, 2u},
	{   &Os_TickCounter, 40u, 8u, 3u},
	{   &Os_TickCounter, 1u, 1u, 4u}
};

/* %PCMS_HEADER_SUBSTITUTION_START:%
 ******************************************************************************
 * Document Management Information Log (generated by Dimensions CM)
 *
 * Description:
 * %PD:%
 *
 * Used by Baselines:
 * %PIRB:%
 *
 * Used by Dimensions CM Projects:
 * %PIRW:%
 *
 * Change History:
 * %PL:%
 *
 * %PCMS_HEADER_SUBSTITUTION_END:%
 */
