/*                                                           
 ******************************************************************************
 *
 * \par Module Owner:
 *   Huf H&uuml;lsbeck & F&uuml;rst GmbH & Co. KG \n
 *   Steeger Str. 17 \n
 *   42551 Velbert \n
 *   Department PDE-S
 *
 ******************************************************************************
 * \par Description:
 * Generated configuration file for TimeService
 * Implementation based on Huf BSW specifications  \n
 *
 * %PCMS_HEADER_SUBSTITUTION_START:%
 ******************************************************************************
 * Document Management Information Log (generated by Dimensions CM)
 *
 *
 *  CM Item:   %PID:%
 *  Itemname:  %PM:%
 *  Location:  %ARCHIVE:%
 *  Revision:  %PR:%
 *  Date:      %DATE:%
 *  Author:    %AUTHOR:%
 *
 * %PCMS_HEADER_SUBSTITUTION_END:%
 *
 ******************************************************************************/
#ifndef TIME_SERVICE_CFG_H		/* To avoid double inclusion */
#define TIME_SERVICE_CFG_H

#include "Std_Types.h"
#include "Gpt.h"

/* TimeServGeneral */
/* Data types depend on the uc used */
typedef Gpt_PredefTimerType Tm_PredefTimerType;
typedef U32 Tm_PredefTimerRefTimeType;

/* Define the macro used to address the predefined free-running timer of 1us from GPT */
#define PREDEFINED_TIMER		GPT_PREDEF_TIMER_1US_16BIT

/* Define the macro used to address the interrupt flag of the predefined free-running timer of 1us from GPT  */
#define TM_TIMER_INT							REG_BIT_GET32(FTM_SC_ADDR32(0), FTM_SC_TOF_MASK_U32)
#define TM_CLEAR_TIMER_PENDING_INT		REG_BIT_CLEAR32(FTM_SC_ADDR32(0), FTM_SC_TOF_MASK_U32)

/* polyspace-begin MISRA-C3:2.5 [Not a defect:Unset] "The macros can be used when integrating the module" */
#define TM_16BIT_TIMER_ENABLE		STD_OFF

/* The list of 32bits software timers configured by the user */
#define NFC_Generic_timer_0		0u
#define NFC_Generic_timer_1		1u
#define NFC_Generic_timer_2		2u
#define NFC_Generic_timer_3		3u
#define NFC_Generic_timer_4		4u
#define NFC_Generic_timer_5		5u
#define NFC_Generic_timer_6		6u
#define NFC_Generic_timer_7		7u
#define NFC_Generic_timer_8		8u
#define NFC_Generic_timer_9		9u
#define NO_OF_32BIT_SWT_U8		10u
#define TM_32BIT_TIMER_ENABLE		STD_ON

/* The list of 32bits software timers configured by the user */
#define NFC_diagnostic_SlowTimer_1ms		0u
#define ISO_TP_RECEPTION_TIMER		1u
#define ISO_TP_TRANSMISSION_TIMER		2u
#define NfcFuncGateway_Wakeup_Timer		3u
#define NfcFuncGateway_PollingDelay_Timer		4u
#define NfcFuncGateway_LpcdCalibration_Timer		5u
#define NfcFuncGateway_WaitingCommError_Timer		6u
#define NfcFuncGateway_RetryAuthenticationRequest_Timer		7u
#define NfcFuncGateway_SilentDevicePresenceCheck_Timer		8u
#define NfcFuncGateway_Routing_Timer		9u
#define NfcFuncGateway_Transmit_Timer		10u
#define NfcFuncGateway_ActivateESM_Timer		11u
#define NfcFuncGateway_KeepNfcDeviceSignalOn_Timer		12u
#define NO_OF_SLOW_SWT_U8		13u
#define TM_SLOW_TIMER_ENABLE		STD_ON
/* polyspace-end MISRA-C3:2.5 [Not a defect:Unset] "The macros can be used when integrating the module" */

#endif /* TIME_SERVICE_CFG_H */

/* %PCMS_HEADER_SUBSTITUTION_START:%
 ******************************************************************************
 * Document Management Information Log (generated by Dimensions CM)
 *
 *  Description:
 *  %PD:%
 *
 *  Used by Baselines:
 *  %PIRB:%
 *
 *  Used by Dimensions CM Projects:
 *  %PIRW:%
 *
 *  Change History:
 *  %PL:%
 *
 * %PCMS_HEADER_SUBSTITUTION_END:%
 */
